tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary-fixed-dim": "#88cff9",
                "on-secondary-fixed": "#131b2e",
                "inverse-primary": "#03658a",
                "inverse-on-surface": "#2d3132",
                "on-primary": "#00344a",
                "tertiary-fixed-dim": "#7bd0ff",
                "outline-variant": "#40484e",
                "background": "#101415",
                "tertiary-fixed": "#c4e7ff",
                "on-primary-fixed-variant": "#004c69",
                "surface-container-highest": "#313536",
                "on-tertiary-fixed-variant": "#004c69",
                "on-surface-variant": "#bfc8cf",
                "surface-container": "#1d2022",
                "secondary-fixed-dim": "#bec6e0",
                "error": "#ffb4ab",
                "surface-container-high": "#272b2c",
                "surface-bright": "#363a3b",
                "surface-container-lowest": "#0b0f10",
                "on-primary-fixed": "#001e2c",
                "on-tertiary": "#00354a",
                "on-secondary-fixed-variant": "#3e465c",
                "on-secondary-container": "#adb5ce",
                "on-background": "#e0e3e4",
                "secondary": "#bec6e0",
                "on-tertiary-container": "#005d7f",
                "on-error": "#690005",
                "outline": "#87929a",
                "primary-container": "#8ed5ff",
                "on-surface": "#e0e3e4",
                "surface-container-low": "#181c1d",
                "secondary-container": "#3e465c",
                "on-primary-container": "#005d7f",
                "primary-fixed": "#c4e7ff",
                "surface-tint": "#88cff9",
                "surface": "#101415",
                "error-container": "#93000a",
                "tertiary": "#d1ecff",
                "primary": "#d2ecff",
                "inverse-surface": "#e0e3e4",
                "tertiary-container": "#8cd5ff",
                "secondary-fixed": "#dae2fd",
                "on-tertiary-fixed": "#001e2c",
                "surface-dim": "#101415",
                "surface-variant": "#313536",
                "on-error-container": "#ffdad6",
                "on-secondary": "#283044",
                "neon-purple": "#bc00ff",
                "neon-cyan": "#00f2ff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-mobile": "16px",
                "lg": "48px",
                "sm": "12px",
                "margin-desktop": "64px",
                "xl": "80px",
                "md": "24px",
                "xs": "4px",
                "base": "8px",
                "max-width": "1440px",
                "gutter": "24px"
            },
            "fontFamily": {
                "headline-md": ["Plus Jakarta Sans"],
                "title-lg": ["Plus Jakarta Sans"],
                "label-md": ["Plus Jakarta Sans"],
                "headline-sm": ["Plus Jakarta Sans"],
                "body-sm": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "code-sm": ["JetBrains Mono"],
                "body-md": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"]
            },
            "fontSize": {
                "headline-md": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "code-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
            }
        },
    },
};
